List<bool> expertFoul = [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
];
List<bool> brownBlackFoul = [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];
List<bool> bluePurpleFoul = [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];
List<bool> whiteFoul = [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];
List<bool> u16Foul = [
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];
List<bool> u12Foul = [
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];

List<String> foulListMn = [
  'Хөл дэлгэж сунгах',
  'Хүзүү хөшиж боох',
  'Хөл шулуун татах',
  'Өөрийн ханцуйг ашиглан боох (Ezequiel)',
  'Guillotine',
  'Мөрөнд өчих (Omoplata)',
  'Гурвалжин боолтноос толгой татах',
  'Гарын гурвалжин боолт',
  'Хавирга бөөрийг хөлөөрөө хавчиж шахах',
  'Бугуйнд өчих',
  'Дан хамах мэхийг хийж буй тамирчны толгой өрсөлдөгчийнх нь биеийн гадна талд байрлах',
  'Гарын нугарах хэсгээр хоёр толгойт булчинг шахах',
  'Өвдөгний нугарах зүгийн эсрэг дарах',
  'Унагааж савах',
  'Хүзүү дангаар нь хөших',
  'Өсгийг эргүүлэн өвдөгөнд өчих (Heel hook)',
  'Өвдөг эргүүлсэн аливаа өчиг',
  'Өвдөгний үеэр хөл давуулах',
  'Босоогоос хайчилж унагаах',
  'Хөл шулуун татаж байх үедээ өрсөлдөгчийхөө эсрэг талын хөл тал руу эргэх',
  'Гараа ашиглан хөлнөөс барьж шагайнд өчих үедээ шагайн үений эсрэг дарах',
  'Хурууг арагш дараж татах',
  'Өрсөлдөгч нь дан хамах мэх хийж байх үед бүснээс нь барин биеийнхээ гадна талаар давуулж толгойгоор нь унагаах',
  'Өрсөлдөгчөө арагш давуулж шидэн толгой, хүзүүгээр нь унагаах',
];

List<String> foulList = [
  'Submission stretching the legs apart',
  'Choke with spinal lock',
  'Straight foot lock',
  'Forearm choke using the sleeve (Ezequiel)',
  'Frontal guillotine choke',
  'Omoplata',
  'Triangle (pulling head)',
  'Arm triangle',
  'Lock inside the closed guard with legs compressing kidneys or ribs',
  'Wrist lock',
  'Single leg takedown placing the head outside body',
  'Biceps slicer',
  'Knee bar',
  'Slam',
  'Spinal lock',
  'Heel hook',
  'Locks twisting the knees',
  'Knee ripping',
  'Scissor takedown',
  'In straight foot lock, turning in the direction of the foot not under attack',
  'In the toe hold, applying outward pressure on the foot',
  'Bending fingers backwards',
  'Grab the opponents belt and throw him to the floor on his head when defending a single leg situation while his opponents head is on outside of his body',
  'Suplex takedown technique, landing with the opponents head or neck on the ground',
];
